revoke delete on table "public"."employees" from "anon";

revoke insert on table "public"."employees" from "anon";

revoke references on table "public"."employees" from "anon";

revoke select on table "public"."employees" from "anon";

revoke trigger on table "public"."employees" from "anon";

revoke truncate on table "public"."employees" from "anon";

revoke update on table "public"."employees" from "anon";

revoke delete on table "public"."employees" from "authenticated";

revoke insert on table "public"."employees" from "authenticated";

revoke references on table "public"."employees" from "authenticated";

revoke select on table "public"."employees" from "authenticated";

revoke trigger on table "public"."employees" from "authenticated";

revoke truncate on table "public"."employees" from "authenticated";

revoke update on table "public"."employees" from "authenticated";

revoke delete on table "public"."employees" from "service_role";

revoke insert on table "public"."employees" from "service_role";

revoke references on table "public"."employees" from "service_role";

revoke select on table "public"."employees" from "service_role";

revoke trigger on table "public"."employees" from "service_role";

revoke truncate on table "public"."employees" from "service_role";

revoke update on table "public"."employees" from "service_role";

alter table "public"."employees" drop constraint "employees_pkey";

drop index if exists "public"."employees_pkey";

drop table "public"."employees";

create table "public"."transaction1" (
    "id" bigint generated by default as identity not null,
    "transactiondate" date,
    "category" text,
    "amount" bigint,
    "description" text,
    "type" text
);


alter table "public"."transaction" add column "category" text;

CREATE UNIQUE INDEX transaction1_pkey ON public.transaction1 USING btree (id);

alter table "public"."transaction1" add constraint "transaction1_pkey" PRIMARY KEY using index "transaction1_pkey";

grant delete on table "public"."transaction1" to "anon";

grant insert on table "public"."transaction1" to "anon";

grant references on table "public"."transaction1" to "anon";

grant select on table "public"."transaction1" to "anon";

grant trigger on table "public"."transaction1" to "anon";

grant truncate on table "public"."transaction1" to "anon";

grant update on table "public"."transaction1" to "anon";

grant delete on table "public"."transaction1" to "authenticated";

grant insert on table "public"."transaction1" to "authenticated";

grant references on table "public"."transaction1" to "authenticated";

grant select on table "public"."transaction1" to "authenticated";

grant trigger on table "public"."transaction1" to "authenticated";

grant truncate on table "public"."transaction1" to "authenticated";

grant update on table "public"."transaction1" to "authenticated";

grant delete on table "public"."transaction1" to "service_role";

grant insert on table "public"."transaction1" to "service_role";

grant references on table "public"."transaction1" to "service_role";

grant select on table "public"."transaction1" to "service_role";

grant trigger on table "public"."transaction1" to "service_role";

grant truncate on table "public"."transaction1" to "service_role";

grant update on table "public"."transaction1" to "service_role";


